version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/quantlib
    links:
      - db:mongodb
    container_name: quantlib
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: quantlib_db
    ports:
      - "27017:27017"